version: '3'

services:
   
  nginx:
    container_name: nginx_container
    image: nginx
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - $PWD/nginx/conf/nginx.conf:/etc/nginx/nginx.conf           
      - $PWD/nginx/logs/:/var/log/nginx/
      - $PWD/nginx/data/:/var/share/nginx/html/ 